version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile  # <-- caminho correto aqui!
    container_name: places-api-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - postgres


  postgres:
    image: postgres:15
    ports:
      - "5544:5432"
    environment:
      POSTGRES_DB: places_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


